/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2015-06-05 13:43:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import net.simflow.ssp.*;

public final class SearchResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/search.jsp", Long.valueOf(1433509631000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("net.simflow.ssp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>搜索结果</title>\n");
      out.write("<!-- Bootstrap core CSS\n");
      out.write("   \n");
      out.write(" -->\n");
      out.write("  <link href=\"dist/css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("      <script type=\"text/javascript\" src=\"dist/js/jquery.js\"></script>  \n");
      out.write("   <script type=\"text/javascript\" src=\"dist/js/bootstrap.js\"></script>\n");
      out.write("    <!-- Custom styles for this template -->\n");
      out.write("  <!-- <link href=\"signin.css\" rel=\"stylesheet\"> \n");
      out.write("    <link href=\"square.css\" rel=\"stylesheet\">\n");
      out.write("-->  \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<header class=\"navbar navbar-inverse navbar-fixed-top bs-docs-nav\" role=\"banner\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <nav class=\"collapse navbar-collapse bs-navbar-collapse\" role=\"navigation\">\n");
      out.write("      <ul class=\"nav navbar-nav\">\n");
      out.write("        <li  class=\"active\">\n");
      out.write("          <a><font color=yellow size=4>智能服务平台</font></a>\n");
      out.write("        \n");
      out.write("      </ul>\n");
      out.write("      <ul class=\"nav navbar-nav\">\n");
      out.write("        <li  class=\"active\">\n");
      out.write("          <li>\n");
      out.write("          <a href=\"MainPage.jsp\">首页</a>\n");
      out.write("          </li>\n");
      out.write("        \n");
      out.write("      </ul>\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\n");
      out.write(" ");

      if((request.getSession()).getValue("LogInUser")!=null){
      out.println("<li>");
      out.println("<a href=\"/Smart_Service_Platform/UserInfo.jsp?userid="+((User)(request.getSession()).getValue("LogInUser")).getid()+"\"target=\"_blank\">您好,"+((User)(request.getSession()).getValue("LogInUser")).getName()+"</a>");
      out.println("</li>");
      out.println("<li>");
      out.println("<a href=\"/Smart_Service_Platform/servlet/LogOut\">注销</a>");
      out.println("</li>");
      }
      else{
      out.println("<li>");
      out.println("<a href=\"/Smart_Service_Platform/Login.jsp\">登录</a>");
      out.println("</li>");
      out.println("<li>");
      out.println("<a href=\"/Smart_Service_Platform/Register.jsp\">注册</a>");
      out.println("</li>");
      }     
       
      out.write("\n");
      out.write("\n");
      out.write("      </ul>\n");
      out.write("    </nav>\n");
      out.write("  </div>\n");
      out.write("</header>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<div class=\"container\">\n");
      out.write("   \n");
      out.write("       <div class=\"col-md-4\">\n");
      out.write("\n");
      out.write("       ");

       out.println("<h4>已注册服务</h4>");
       out.println("<hr>");
       out.println("<h4>平台服务</h4>");
       out.println("<hr>");
       ArrayList platservicelist=new ArrayList<PlatService>();
       PlatServiceDAO platservicedao=new PlatServiceDAO();
       platservicelist=platservicedao.GetGlobalLatestPlatService(5);
       for(int i=0;i<platservicelist.size();i++){
			out.println("<h5>"+"<a href=\""+((PlatService)(platservicelist.get(i))).getplatserviceurl()+"\"target=\"_blank\">"+((PlatService)(platservicelist.get(i))).getplatservicename()+"</a><br>"+"</h5>");
			out.println("<h6>"+((PlatService)(platservicelist.get(i))).getcontent()+"</h6>");
			out.println("<p>"+((PlatService)(platservicelist.get(i))).getbirthday()+"</p>");
       }
       
       out.println("<hr>");
       out.println("<h4>酒店服务</h4>");
       out.println("<hr>");
       ArrayList hotelservicelist=new ArrayList<HotelService>();
       HotelServiceDAO hotelservicedao=new HotelServiceDAO();
       hotelservicelist=hotelservicedao.GetGlobalLatestHotelService(5);
       for(int i=0;i<hotelservicelist.size();i++){
			out.println("<h5>"+"<a href=\""+((HotelService)(hotelservicelist.get(i))).gethotelurl()+"\"target=\"_blank\">"+((HotelService)(hotelservicelist.get(i))).gethotelservicename()+"</a><br>"+"</h5>");
			out.println("<h6>"+"最低价："+((HotelService)(hotelservicelist.get(i))).gethotelprice()+"；"+((HotelService)(hotelservicelist.get(i))).gethoteltype()+"；"+((HotelService)(hotelservicelist.get(i))).gethotelarea()+"</h6>");
			out.println("<h6>"+((HotelService)(hotelservicelist.get(i))).gethoteladd()+"</h6>");
			out.println("<IMG alt=\"\" src="+((HotelService)(hotelservicelist.get(i))).gethotelpic()+" width=\"200\" />");
       }
		
      out.write("\n");
      out.write("\t\t<hr>\n");
      out.write("\t  \t</div>\n");
      out.write("\t  \t\n");
      out.write("        <div class=\"col-md-4\">               \n");
      out.write("   \t\t");
      out.write("\n");
      out.write("\n");
      out.write("       <form  class=\"form-signin\" role=\"form\" id=\"searchservice\" action=\"/Smart_Service_Platform/SearchResult.jsp\" method=\"service\">\n");
      out.write("    <h4>搜索服务</h4>\n");
      out.write("    <input id=\"SearService\" name=\"SearService\" type=\"text\"  class=\"form-control\" placeholder=\"请输入要搜索的服务\" required >\n");
      out.write("    <br>\n");
      out.write("   <button type=\"submit\" class=\"btn btn-sm btn-primary\">搜索</button>\n");
      out.write("    </form>");
      out.write("\n");
      out.write("\n");
      out.write("   \t\t");
 
   		request.setCharacterEncoding("utf-8");
   		PlatServiceDAO platservicedaosearch=new PlatServiceDAO();
	    String SearchPlatService=(String)request.getParameter("SearService");	     
	    ArrayList platal=new ArrayList<PlatService>();
		platal=platservicedaosearch.SearchPlatService(SearchPlatService);
		out.println("<hr>");
		if (platal.size() == 0) {
       		out.println("<h4> 没有符合条件的平台服务。。</h4>");
       		out.println("<hr>");
       	} else {
      	out.println("<h4> 符合条件的平台服务:</h4>");
       	out.println("<hr>");
       	int size = platal.size();
       	if (platal.size()>=10) {
       		size = 10;
       	}
       	for(int i=0;i<size;i++){
			//out.println("<h3>"+((PlatService)(platal.get(i))).getownername()+"</h3>");
			out.println("<h5>"+"<a href=\""+((PlatService)(platal.get(i))).getplatserviceurl()+"\"target=\"_blank\">"+((PlatService)(platal.get(i))).getplatservicename()+"</a><br>"+"</h5>");
			//out.println("<h3>"+"<a href=\"/Smart_Service_Platform/UserInfo.jsp?userid="+((PlatService)(platal.get(i))).getownid()+"\">"+((PlatService)(platal.get(i))).getownername()+"</a><br>"+"</h3>");
			out.println("<h6>"+((PlatService)(platal.get(i))).getcontent()+"</h6>");
			out.println("<p>"+((PlatService)(platal.get(i))).getbirthday()+"</p>");
        }  
        out.println("<hr>");
       	}
       	
       	HotelServiceDAO hotelservicedaosearch=new HotelServiceDAO();
	    String SearchHotelService=(String)request.getParameter("SearService");	     
	    ArrayList hotelal=new ArrayList<HotelService>();
		hotelal=hotelservicedaosearch.SearchHotelService(SearchHotelService);
       	if (hotelal.size() == 0) {
       		out.println("<h4> 没有符合条件的酒店服务。。</h4>");
       		out.println("<hr>");
       	} else {
      	out.println("<h4> 符合条件的酒店服务:</h4>");
       	out.println("<hr>");
       	int size = hotelal.size();
       	if (hotelal.size()>=10) {
       		size = 10;
       	}
        for(int i=0;i<size;i++){
			//out.println("<h3>"+((HotelService)(hotelal.get(i))).getownername()+"</h3>");
			out.println("<h5>"+"<a href=\""+((HotelService)(hotelal.get(i))).gethotelurl()+"\"target=\"_blank\">"+((HotelService)(hotelal.get(i))).gethotelservicename()+"</a><br>"+"</h5>");
			//out.println("<h3>"+"<a href=\"/Smart_Service_Hotelform/UserInfo.jsp?userid="+((HotelService)(hotelal.get(i))).getownid()+"\">"+((HotelService)(hotelal.get(i))).getownername()+"</a><br>"+"</h3>");
			out.println("<h6>"+"最低价："+((HotelService)(hotelal.get(i))).gethotelprice()+"；"+((HotelService)(hotelal.get(i))).gethoteltype()+"；"+((HotelService)(hotelal.get(i))).gethotelarea()+"</h6>");
			out.println("<h6>"+((HotelService)(hotelal.get(i))).gethoteladd()+"</h6>");
			out.println("<IMG alt=\"\" src="+((HotelService)(hotelal.get(i))).gethotelpic()+" width=\"200\" />");
        }  
        out.println("<hr>");
       	}
  
         
      out.write("\n");
      out.write("    \t</div>\n");
      out.write("    \t\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("        ");

        out.println("<h4>服务推荐</h4>");
        out.println("<hr>");
        out.println("<h4>平台服务</h4>");
        out.println("<hr>");
        ArrayList platservicelistrec=new ArrayList<PlatService>();
        PlatServiceDAO platservicedaorec=new PlatServiceDAO();
        platservicelistrec=platservicedaorec.GetGlobalLatestPlatService(5);
        for(int i=0;i<platservicelistrec.size();i++){
 			out.println("<h5>"+"<a href=\""+((PlatService)(platservicelistrec.get(i))).getplatserviceurl()+"\"target=\"_blank\">"+((PlatService)(platservicelistrec.get(i))).getplatservicename()+"</a><br>"+"</h5>");
 			out.println("<h6>"+((PlatService)(platservicelistrec.get(i))).getcontent()+"</h6>");
 			out.println("<p>"+((PlatService)(platservicelistrec.get(i))).getbirthday()+"</p>");
        }
        
        out.println("<hr>");
        out.println("<h4>酒店服务</h4>");
        out.println("<hr>");
        ArrayList hotelservicelistrec=new ArrayList<HotelService>();
        HotelServiceDAO hotelservicedaorec=new HotelServiceDAO();
        hotelservicelistrec=hotelservicedaorec.GetGlobalLatestHotelService(5);
        for(int i=0;i<hotelservicelistrec.size();i++){
 			out.println("<h5>"+"<a href=\""+((HotelService)(hotelservicelistrec.get(i))).gethotelurl()+"\"target=\"_blank\">"+((HotelService)(hotelservicelistrec.get(i))).gethotelservicename()+"</a><br>"+"</h5>");
 			out.println("<h6>"+"最低价："+((HotelService)(hotelservicelistrec.get(i))).gethotelprice()+"；"+((HotelService)(hotelservicelistrec.get(i))).gethoteltype()+"；"+((HotelService)(hotelservicelistrec.get(i))).gethotelarea()+"</h6>");
 			out.println("<h6>"+((HotelService)(hotelservicelistrec.get(i))).gethoteladd()+"</h6>");
 			out.println("<IMG alt=\"\" src="+((HotelService)(hotelservicelistrec.get(i))).gethotelpic()+" width=\"200\" />");
        }
		
      out.write("\n");
      out.write("\t\t<hr>\n");
      out.write("      \t</div>     \n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("         \n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
